//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTEST()
        {
            this.CONTEST_FEES = new HashSet<CONTEST_FEES>();
            this.EXAMINATIONCOUNCIL_STAFFS = new HashSet<EXAMINATIONCOUNCIL_STAFFS>();
            this.LOCATIONS = new HashSet<LOCATION>();
            this.REGISTERS = new HashSet<REGISTER>();
            this.SCHEDULES = new HashSet<SCHEDULE>();
            this.SHIFTS = new HashSet<SHIFT>();
            this.ORIGINAL_TESTS = new HashSet<ORIGINAL_TESTS>();
        }
    
        public int ContestID { get; set; }
        public string ContestName { get; set; }
        public string Description { get; set; }
        public int CreatedDate { get; set; }
        public Nullable<int> EndDate { get; set; }
        public Nullable<int> AcceptedDate { get; set; }
        public int BeginRegistration { get; set; }
        public int EndRegistration { get; set; }
        public int CreatedQuestionStartDate { get; set; }
        public int CreatedQuestionEndDate { get; set; }
        public string SchoolYear { get; set; }
        public int Status { get; set; }
        public Nullable<int> CreatedStaffID { get; set; }
        public Nullable<int> AcceptedStaffID { get; set; }
        public Nullable<int> BeginDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTEST_FEES> CONTEST_FEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMINATIONCOUNCIL_STAFFS> EXAMINATIONCOUNCIL_STAFFS { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual STAFF STAFF1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTER> REGISTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULE> SCHEDULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFT> SHIFTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORIGINAL_TESTS> ORIGINAL_TESTS { get; set; }
    }
}
