//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORIGINAL_TEST_DETAILS
    {
        public int OriginalTestDetailID { get; set; }
        public int NumberIndex { get; set; }
        public int Status { get; set; }
        public int OriginalTestID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual ORIGINAL_TESTS ORIGINAL_TESTS { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}
