//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION_TYPES()
        {
            this.QUESTIONS = new HashSet<QUESTION>();
        }
    
        public int QuestionTypeID { get; set; }
        public string QuestionTypeName { get; set; }
        public string Description { get; set; }
        public bool IsSingleChoice { get; set; }
        public bool IsParagraph { get; set; }
        public bool IsQuestionContent { get; set; }
        public int NumberSubQuestion { get; set; }
        public int NumberAnswer { get; set; }
        public int Status { get; set; }
        public bool IsQuiz { get; set; }
        public Nullable<int> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTION> QUESTIONS { get; set; }
    }
}
