//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        public int ReceiptID { get; set; }
        public Nullable<double> Cost { get; set; }
        public int ReceivedDate { get; set; }
        public int RegisteredDate { get; set; }
        public bool ReceiptType { get; set; }
        public int Status { get; set; }
        public int StaffID { get; set; }
        public int RegisterID { get; set; }
    
        public virtual REGISTER REGISTER { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
