//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTER()
        {
            this.CONTESTANTS = new HashSet<CONTESTANT>();
            this.RECEIPTS = new HashSet<RECEIPT>();
            this.REGISTERS_SUBJECTS = new HashSet<REGISTERS_SUBJECTS>();
        }
    
        public int RegisterID { get; set; }
        public string StudentCode { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DOB { get; set; }
        public string Ethnic { get; set; }
        public string PlaceOfBirth { get; set; }
        public string HighSchool { get; set; }
        public Nullable<int> Sex { get; set; }
        public string IdentityCardNumber { get; set; }
        public string Unit { get; set; }
        public string CurrentAddress { get; set; }
        public int RegisteredDate { get; set; }
        public Nullable<int> RegisteredType { get; set; }
        public Nullable<int> TrainingSystem { get; set; }
        public Nullable<int> LevelsOfTraining { get; set; }
        public byte[] Image { get; set; }
        public int Status { get; set; }
        public int ContestID { get; set; }
        public Nullable<int> ContestantTypeID { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
    
        public virtual CONTESTANT_TYPES CONTESTANT_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTESTANT> CONTESTANTS { get; set; }
        public virtual CONTEST CONTEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTERS_SUBJECTS> REGISTERS_SUBJECTS { get; set; }
    }
}
