//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDER
    {
        public int ReminderID { get; set; }
        public string ReminderContent { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> EndDate { get; set; }
        public int Status { get; set; }
        public int SendStaffID { get; set; }
        public int ReceiveStaffID { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        public virtual STAFF STAFF1 { get; set; }
    }
}
