//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRUCTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STRUCTURE()
        {
            this.STRUCTURE_DETAILS = new HashSet<STRUCTURE_DETAILS>();
        }
    
        public int StructureID { get; set; }
        public int CreatedDate { get; set; }
        public int Status { get; set; }
        public int ScheduleID { get; set; }
        public int CreatedStaffID { get; set; }
    
        public virtual SCHEDULE SCHEDULE { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRUCTURE_DETAILS> STRUCTURE_DETAILS { get; set; }
    }
}
