//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRUCTURE_DETAILS
    {
        public int StructureDetailID { get; set; }
        public int NumberQuestions { get; set; }
        public int Level { get; set; }
        public double Score { get; set; }
        public int Status { get; set; }
        public int StructureID { get; set; }
        public int TopicID { get; set; }
    
        public virtual STRUCTURE STRUCTURE { get; set; }
        public virtual TOPIC TOPIC { get; set; }
    }
}
