//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_DETAILS()
        {
            this.ANSWERSHEET_DETAILS = new HashSet<ANSWERSHEET_DETAILS>();
        }
    
        public int TestDetailID { get; set; }
        public string RandomAnswer { get; set; }
        public int NumberIndex { get; set; }
        public double Score { get; set; }
        public int Status { get; set; }
        public int TestID { get; set; }
        public int QuestionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSHEET_DETAILS> ANSWERSHEET_DETAILS { get; set; }
        public virtual QUESTION QUESTION { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
